CREATE TABLE VENUE (
    LEVEL_ID NUMERIC(12) IDENTITY NOT NULL PRIMARY KEY,
    LEVEL_NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL NOT NULL,
    NUMBER_OF_ROWS NUMERIC(12) NOT NULL,
    SEATS_IN_ROW NUMERIC(12) NOT NULL
);

CREATE TABLE CUSTOMER (
    ID NUMERIC(12) IDENTITY NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE SEAT_HOLD (
    ID NUMERIC(12) IDENTITY NOT NULL PRIMARY KEY,
    CUSTOMER_ID NUMERIC(12) NOT NULL,
    HOLD_TIME TIMESTAMP DEFAULT NULL,
    BOOKING_CODE VARCHAR(300),
    BOOKING_TIME TIMESTAMP DEFAULT NULL,
);

CREATE TABLE SEAT_BOOKING (
    ID NUMERIC(12) IDENTITY NOT NULL PRIMARY KEY,
    HOLD_ID NUMERIC(12) NOT NULL,
    VENUE_ID NUMERIC(12) NOT NULL,
    NUMBER_OF_SEATS NUMERIC(12) NOT NULL,
);

ALTER TABLE SEAT_HOLD
    ADD CONSTRAINT "CUSTOMER_SEAT_HOLD_FK"
    FOREIGN KEY ("CUSTOMER_ID")
    REFERENCES "CUSTOMER"("ID");

ALTER TABLE SEAT_BOOKING
    ADD CONSTRAINT "SEAT_HOLD_FK"
    FOREIGN KEY ("HOLD_ID")
    REFERENCES "SEAT_HOLD"("ID")
ALTER TABLE SEAT_BOOKING
    ADD CONSTRAINT "VENUE_BOOKING_FK"
    FOREIGN KEY ("VENUE_ID")
    REFERENCES "VENUE"("LEVEL_ID")